# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 05:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=16, unique=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30, unique=True)),
                ('last_name', models.CharField(max_length=30, unique=True)),
                ('tmp_password', models.CharField(blank=True, max_length=30, null=True)),
                ('flag_for_change', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', myapp.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoadMap',
            fields=[
                ('rd_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 5, 25, 5, 15, 27, 2704, tzinfo=utc))),
                ('points', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('in_progress', 'in_progress'), ('ready', 'ready')], default='in_progress', max_length=11)),
                ('estimate', models.DateField(default=django.utils.timezone.now)),
                ('my_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('road_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='myapp.RoadMap')),
            ],
            options={
                'ordering': ['state', 'estimate'],
            },
        ),
        migrations.AddField(
            model_name='scores',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Task'),
        ),
    ]
